### ISSUE TITLE
"Remote control"

### ISSUE THREAD

**Issue by jskunkle** [dakboard/Hardware-OS#10]
It would be really nice to have a "remote control" for our dakboard - either a "remote" app on a mobile device or even better a programmable remote control of some sort (TV remote, wall mount, etc).  It would be really nice to switch "instantly" between screens and turn the dakboard off and on.  

Examples of how my family would use it:

* We need a detailed calendar view = switch to screen 1
* We just want to view big photos = switch to screen 3
* We need "details/dense text" (bank account balances, asana todos, etc) = screen x 

Thanks!

**Comment by cocarrig** [comment]
Hi jskunkle,

With the deployment of button functionality in DAKboard, the remaining requirement for fulfilling this use case is an input device to your display device:
https://blog.dakboard.com/qr-codes-buttons-and-calendar-style-updates/

For a Raspberry Pi running DAKboard OS, this can be a touch screen or any number of RF/infrared USB touchpad/Keyboards that are readily available and compatible with linux.

If deployed on an iPad or other tablet, no other hardware is necessary, and a button can be deployed to flip from one screen on another to show other content.

Since we are migrating requests of these types to Discussions in github, if you have any follow up questions please create a discussion there or email us at contact@dakboard.com and we can help you further.
