### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by mwkrieger** [dakboard/Hardware-OS#14]
I think this has been asked for before, but I thought I would bring it up again. It'd be great to have touchscreen support to be able to add things like pages, buttons, and that sort of thing to the system. 

My specific use case would be to add a button to trigger my Hue lights to come on. Another use case would be to be able to use those buttons with other webhooks like in IFTT. 

Something more pedestrian would be the ability to hit the 'reload' button when Dakboard shows the 'oh, snap' page and I have to unplug/replug the display to reset things.

**Comment by cocarrig** [comment]
The raspberry pi does natively support touchscreen if a linux capable touchscreen with USB connection is used. Because of this touchscreen is supported by the hardware generally speaking in DAKboard OS with the right paired hardware. Multitouch capability will be made dependent upon if that capability is made to the underlying Raspbian OS being used on the DAKboard OS, which we would consider pursuing in the URL if added. Based on the comments in this thread the DAKboard screen URL capabilities are the primary focus, so I'd like to point towards some progress on this front and where things are going:

Switching between screen/Calendars/links:
Recent enhancements for new buttons in DAKboard provide much of this capability by allowing you to switch between screens that have differently configured calendars and outside of DAKboard screen capabilities. Check out the following blog article on this that explains the button feature more and try it out:
https://blog.dakboard.com/qr-codes-buttons-and-calendar-style-updates/

Feel free to create a discussion in this repo to talk this through further or reach out to us at contact@dakboard.com
