### ISSUE TITLE
Please Host releases with Github

### ISSUE THREAD

**Issue by ZoltyMat** [dakboard/Hardware-OS#166]
For some reason you're hosting binary files with One Drive, the speed is terrible I am getting around 1mB/s on my 1gb/s up / down connection. 

Just host using github, their speeds are at least normal.

**Comment by cocarrig** [comment]
Apologies for the inconvenience, after the outage Microsoft had a few weeks ago this seems to have been getting slower.  If you instead use the RPi-Imager, that should go faster since its hosted on Google.

If we decide in the future to use Github for more than managing discussions and issues we may consider it for image hosting.
