### ISSUE TITLE
iOS Home Screen issue

### ISSUE THREAD

**Issue by nswilliams** [dakboard/Hardware-OS#22]
I would like to have a full page of web content of screen. The only option is to export to SAVE TO HOME SCREEN. It works nicely on first run. Once pressing to home or jump to other app, it stops working when returning to this screen. Clock is frozen. Maybe JavaScript has bug to freeze when suspended? Workaround: reboot iPhone. Killing app and launch again didn’t help.

**Comment by cocarrig** [comment]
Hi Team,

Unfortunately since options are limited with iOS devices at this time unless an App development effort is pursued, the current options shared previously for configuration are the best options we have on iOS for home screens.  Apologies for the inconvenience on this:
https://dakboard.freshdesk.com/support/solutions/articles/35000133204-use-dakboard-on-an-ipad

We do have many alternative options for android devices using the dakboard App and DAKboard OS on the Raspberry Pi, as well as other detailed in the following link:
https://dakboard.freshdesk.com/support/solutions/folders/35000215639

If future development is completed with iOS devices, we will be sure to notify via the [Blog](blog.dakboard.com).  We will close this case until further notice, but feel free to open a discussion in this repo if you feel other options are available.
