### ISSUE TITLE
DAKboard OS - Update not working

### ISSUE THREAD

**Issue by UXgoesfirst** [dakboard/Hardware-OS#35]
I have just freshly downloaded the OS and installed it on a Raspberry Pi 4GB with a new 32 GB micro SD card.
When I finally recognized that I better have the DAKboard URL at hand during initial set up, the initial set up went okay.
Then the clock had to be updated ... takes a while but then a rebot after the update helps and the screen loads upon boot.

Now comes the housekeeping via raspi-config with hostname, password, SSH, getting the German keyboard set (not covered by initial set up!) ... AND the update. The missing keyboard setting is a pain but having used a US one for years I managed. 
However, the update fails and gives an error message.
How to proceed? Should I bypass raspi-config and go via
- sudo apt-get update
- sudo apt-get upgrade
instead?

Best regards
Christian

**Comment by cocarrig** [comment]
Hi UXgoesfirst,

For a more updated image you may instead want to download DAKboard OS 2.26 available now on the latest buster kernel:
https://dakboard.freshdesk.com/support/solutions/articles/35000125880-download-and-install-the-dakboard-os-for-raspberry-pi

Upgrades that we perform for packages are done via apt-get and then pass a UAT process, however since some applications are deployed in a special manner, this can result in unexpected behavior if you complete them as a warning.  If you run into any issues you can reach out to us at contact@dakboard.com or start a discussion in this repo.  Thanks!
